[versions]
leakcanary = "2.12"
versionCode = "3603030"
versionName = "8.1.3"

sdk-compile = "34"
sdk-min = "26"
sdk-target = "34"

coroutines = "1.7.3"
room = "2.5.2"
prefs = "1.0.1"
materialDialog = "3.3.0"
dagger = "2.48.1"
kotlin = "1.9.10"
compose-compiler = "1.5.3"
media3 = "1.1.1"
agp = "8.1.2"
ktlint-core = "1.0.0"
ktlint-gradlePlugin = "0.5.0"
retrofit = "2.9.0"

[libraries]
androidPluginForGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android-startup", version.ref = "leakcanary" }
leakcanary-plumber = { module = "com.squareup.leakcanary:plumber-android-startup", version.ref = "leakcanary" }
material = "com.google.android.material:material:1.9.0"
ffmpeg = "com.arthenica:ffmpeg-kit-audio:6.0-2"
junit = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.13.8"
paging-runtime = "androidx.paging:paging-runtime-ktx:3.2.1"
paging-compose = "androidx.paging:paging-compose:3.2.1"
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-kotlinx = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
robolectric = "org.robolectric:robolectric:4.10.3"
coil = "io.coil-kt:coil-compose:2.4.0"
appCompat = "androidx.appcompat:appcompat:1.6.1"
constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"
recyclerView = "androidx.recyclerview:recyclerview:1.3.1"
androidxCore = "androidx.core:core-ktx:1.12.0"
kotlin-pluginForGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
desugar = "com.android.tools:desugar_jdk_libs:2.0.3"
documentFile = "androidx.documentfile:documentfile:1.0.1"
koTest-assert = "io.kotest:kotest-assertions-core:5.7.2"
datastore = "androidx.datastore:datastore-preferences:1.0.0"
seismic = "com.squareup:seismic:1.0.3"
viewBinding = { module = "androidx.databinding:viewbinding", version.ref = "agp" }
appStartup = "androidx.startup:startup-runtime:1.1.1"
turbine = "app.cash.turbine:turbine:1.0.0"
molecule = "app.cash.molecule:molecule-runtime:1.2.1"
immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
okhttp = "com.squareup.okhttp3:okhttp:4.11.0"
review = "com.google.android.play:review-ktx:2.0.1"
lottie = "com.airbnb.android:lottie-compose:6.1.0"
clikt = "com.github.ajalt.clikt:clikt:4.2.0"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

firebase-bom = "com.google.firebase:firebase-bom:32.3.1"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-remoteconfig = { module = "com.google.firebase:firebase-config-ktx" }

serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"

room-runtime = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidX-test-runner = "androidx.test:runner:1.5.2"
androidX-test-junit = "androidx.test.ext:junit:1.1.5"
androidX-test-core = "androidx.test:core-ktx:1.5.0"

androidTest-orchestrator = "androidx.test:orchestrator:1.4.2"
androidTest-services-testServices = "androidx.test.services:test-services:1.4.2"
androidTest-services-storage = "androidx.test.services:storage:1.4.2"
androidTest-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidTest-rules = "androidx.test:rules:1.5.0"

conductor = "com.bluelinelabs:conductor:4.0.0-preview-4"

prefs-core = { module = "com.github.PaulWoitaschek.FlowPref:core", version.ref = "prefs" }
prefs-android = { module = "com.github.PaulWoitaschek.FlowPref:android", version.ref = "prefs" }
prefs-inMemory = { module = "com.github.PaulWoitaschek.FlowPref:in-memory", version.ref = "prefs" }

materialDialog-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
materialDialog-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-testUtils-core = { module = "androidx.media3:media3-test-utils", version.ref = "media3" }
media3-testUtils-robolectric = { module = "androidx.media3:media3-test-utils-robolectric", version.ref = "media3" }

lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"

compose-bom = "androidx.compose:compose-bom:2023.09.00"
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-core = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test = { module = "androidx.compose.ui:ui-test" }
compose-ui-testJunit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-activity = "androidx.activity:activity-compose:1.7.2"
compose-navigation = "dev.olshevski.navigation:reimagined:1.5.0"

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
ktlint-core = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint-core" }
ktlint-gradlePlugin = { module = "io.github.usefulness:ktlint-gradle-plugin", version.ref = "ktlint-gradlePlugin" }
ktlint-compose = "io.nlopez.compose.rules:ktlint:0.2.2"

[bundles]
compose = [
  "compose-ui-ui",
  "compose-ui-tooling-preview",
  "compose-foundation",
  "compose-navigation",
  "compose-material-icons-core",
  "compose-material-icons-extended",
  "compose-animation-graphics",
  "compose-animation-animation",
  "androidxCore",
  "compose-material3",
  "compose-activity",
  "coil",
]

testing-jvm = [
  "androidX-test-runner",
  "androidX-test-junit",
  "androidX-test-core",
  "robolectric",
  "coroutines-test",
  "mockk",
  "koTest-assert",
  "turbine",
  "junit"
]

retrofit = [
  "retrofit-core",
  "retrofit-scalars",
  "retrofit-kotlinx"
]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
anvil = { id = "com.squareup.anvil", version = "2.4.8-1-8" }
ktlint = { id = "io.github.usefulness.ktlint-gradle-plugin", version.ref = "ktlint-gradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.10-1.0.13" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
googleServices = { id = "com.google.gms.google-services", version = "4.3.15" }
playPublish = { id = "com.github.triplet.play", version = "3.8.4" }
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
