[versions]
coroutines = "1.5.1"
room = "2.3.0"
conductor = "3.1.1"
prefs = "1.0.1"
materialDialog = "3.3.0"
dagger = "2.38.1"
exoPlayer = "2.14.0"
kotlin = "1.5.21"
compose = "1.0.1"

[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:7.0.1"
material = "com.google.android.material:material:1.3.0"
floatingActionButton = "com.getbase:floatingactionbutton:1.10.1"
materialCab = "com.afollestad:material-cab:2.0.1"
picasso = "com.squareup.picasso:picasso:2.8"
tapTarget = "com.getkeepsafe.taptargetview:taptargetview:1.13.0"
lifecycle = "androidx.lifecycle:lifecycle-common-java8:2.3.0"
groupie = "com.xwray:groupie:2.8.1"
ffmpeg = "com.arthenica:mobile-ffmpeg-audio:4.4"
timber = "com.jakewharton.timber:timber:4.7.1"
junit = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.11.0"
truth = "com.google.truth:truth:1.1.2"
robolectric = "org.robolectric:robolectric:4.5.1"
coil = "io.coil-kt:coil-compose:1.3.2"
appCompat = "androidx.appcompat:appcompat:1.3.1"
constraintLayout = "androidx.constraintlayout:constraintlayout:2.0.4"
recyclerView = "androidx.recyclerview:recyclerview:1.1.0"
transitions = "androidx.transition:transition:1.4.0"
palette = "androidx.palette:palette:1.0.0"
media = "androidx.media:media:1.2.1"
androidxCore = "androidx.core:core-ktx:1.6.0"
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
viewModel-savedState = "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1"
viewModel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1"

room-runtime = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidX-test-runner = "androidx.test:runner:1.3.0"
androidX-test-junit = "androidx.test.ext:junit:1.1.2"
androidX-test-core = "androidx.test:core:1.3.0"

conductor-core = { module = "com.bluelinelabs:conductor", version.ref = "conductor" }
conductor-transition = { module = "com.bluelinelabs:conductor-androidx-transition", version.ref = "conductor" }

prefs-core = { module = "com.github.PaulWoitaschek.FlowPref:core", version.ref = "prefs" }
prefs-android = { module = "com.github.PaulWoitaschek.FlowPref:android", version.ref = "prefs" }
prefs-inMemory = { module = "com.github.PaulWoitaschek.FlowPref:in-memory", version.ref = "prefs" }

materialDialog-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
materialDialog-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

exoPlayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoPlayer" }
exoPlayer-flac = { module = "com.github.PaulWoitaschek.ExoPlayer-Extensions:extension-flac", version.ref = "exoPlayer" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material-core = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

[bundles]
compose = [
  "compose-ui-ui",
  "compose-ui-tooling",
  "compose-foundation",
  "compose-material-core",
  "compose-material-icons-core",
  "compose-material-icons-extended",
  "androidxCore",
  "viewModel-savedState",
  "viewModel-compose",
]

