name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call: { }

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/build_setup
      - name: Run Unit Tests + Lint
        run: ./gradlew :app:lintPlayDebug
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: always()
        with:
          name: lint-report
          path: app/build/reports/**/*.html
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/build_setup
      - name: Run Unit Tests + Lint
        run: ./gradlew voiceUnitTest lintKotlin :app:assemblePlayDebug
      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6
        if: always()
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
          check_name: "Unit Tests"

  instrumentation:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/build_setup
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Accept Android Licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
      - name: Setup Managed Devices
        run: ./gradlew voiceDeviceSetup -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
      - name: Run Instrumentation Tests
        run: ./gradlew voiceDeviceGithubDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6
        if: always()
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
          check_name: "Instrumentation Tests"
