name: Trigger Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    environment: trigger-release

    steps:
      - name: Checkout (with tags)
        uses: actions/checkout@v5
        with:
          # We need the tags to determine the next release
          fetch-depth: 0
          fetch-tags: true
          # We need the credentials to push the tag
          persist-credentials: true
          # The standard GITHUB_TOKEN creates no workflow on pushes. That prevents the tag not triggering a release
          token: ${{ secrets.PUSH_PAT }}

      - name: Configure git author
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run release script (non-interactive)
        run: |
          ./scripts/release.main.kts --no-confirm
